# Generated by Django 4.0.4 on 2022-07-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Contacto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(default='link website'),
        ),
        migrations.AlterField(
            model_name='task',
            name='imagen',
            field=models.URLField(default='link-image'),
        ),
    ]
