# Generated by Django 4.0.4 on 2022-07-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_pub_date_task_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
