# Generated by Django 4.0.4 on 2022-07-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_task_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
