# Generated by Django 4.0.4 on 2022-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_task_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.URLField(default='link-image'),
        ),
    ]
