# Generated by Django 4.0.4 on 2022-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('rutas', models.CharField(max_length=200)),
                ('partida', models.CharField(max_length=200)),
                ('llegada', models.CharField(max_length=200)),
                ('contacto', models.IntegerField(null=True)),
                ('imagen', models.URLField(default='link-image')),
                ('link', models.URLField(default='link website')),
                ('release_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(default='12345678'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('C', 'C'), ('U', 'U')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
