# Generated by Django 4.0.4 on 2022-10-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_unidad_user_dni_alter_user_category_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='imagen',
            field=models.URLField(blank=True, default='link-image'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='link',
            field=models.URLField(blank=True, default='link website'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.URLField(blank=True, default='link-image'),
        ),
    ]
