# Generated by Django 4.0.5 on 2022-10-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
